ip no sudoers e conf de /etc/bash.bashrc

diff --git a/roles/config_padrao_labs/tasks/main.yml b/roles/config_padrao_labs/tasks/main.yml
--- a/roles/config_padrao_labs/tasks/main.yml
+++ b/roles/config_padrao_labs/tasks/main.yml
@@ -76,7 +76,7 @@
     path: /etc/sudoers
     state: present
     regexp: '^aluno '
-    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /usr/sbin/ethtool,/usr/sbin/ifconfig,/usr/bin/tcpdump,/usr/sbin/route,/usr/bin/minicom,/usr/sbin/traceroute,/usr/bin/wireshark,/sbin/iwconfig,/usr/sbin/iwlist,/usr/sbin/iw,/etc/init.d/firewall.sh,/usr/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run,/etc/init.d/isc-dhcp-server,/etc/init.d/udev,/usr/bin/rpcgen,/usr/sbin/rfkill'
+    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /usr/sbin/ethtool,/usr/sbin/ifconfig,/usr/bin/tcpdump,/usr/sbin/route,/usr/bin/minicom,/usr/sbin/traceroute,/usr/bin/wireshark,/sbin/iwconfig,/usr/sbin/iwlist,/usr/sbin/iw,/etc/init.d/firewall.sh,/usr/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run,/etc/init.d/isc-dhcp-server,/etc/init.d/udev,/usr/bin/rpcgen,/usr/sbin/rfkill,/usr/bin/ip'
     validate: '/usr/sbin/visudo -cf %s'
   when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')
   tags: sudoers
@@ -600,7 +600,7 @@
     state: present
     path: /etc/bash.bashrc
     line: 'export SHELL=/bin/bash'
-  when: ansible_os_family == 'Debian'
+  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')
 
   #Descomentar o codigo abaixo caso o codigo acima nao funcionar
 - name: Adicionar entrada SHELL export no /etc/security/pam_env.conf - Linux
@@ -608,9 +608,69 @@
     regexp: '^SHELL'
     path: /etc/security/pam_env.conf
     line: 'SHELL     DEFAULT=/bin/bash'
-  when: ansible_os_family == 'Debian'
+  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')
 
 ##################### Fim da configuracao do gdb chamado 2019032610000179
+
+- name: Define conteúdo do /etc/bash.bashrc
+  ansible.builtin.copy:
+    content: |
+      # System-wide .bashrc file for interactive bash(1) shells.
+      # To enable the settings / commands in this file for login shells as well,
+      # this file has to be sourced in /etc/profile.
+      # If not running interactively, don't do anything
+      [ -z "$PS1" ] && return
+
+      # check the window size after each command and, if necessary,
+      # update the values of LINES and COLUMNS.
+      shopt -s checkwinsize
+
+      # set variable identifying the chroot you work in (used in the prompt below)
+      if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
+          debian_chroot=$(cat /etc/debian_chroot)
+      fi
+
+      # set a fancy prompt (non-color, overwrite the one in /etc/profile)
+      # but only if not SUDOing and have SUDO_PS1 set; then assume smart user.
+      if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
+        PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+      fi
+
+      # enable bash completion in interactive shells
+      if ! shopt -oq posix; then
+        if [ -f /usr/share/bash-completion/bash_completion ]; then
+          . /usr/share/bash-completion/bash_completion
+        elif [ -f /etc/bash_completion ]; then
+          . /etc/bash_completion
+        fi
+      fi
+
+      # if the command-not-found package is installed, use it
+      if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
+        function command_not_found_handle {
+                # check because c-n-f could've been removed in the meantime
+                      if [ -x /usr/lib/command-not-found ]; then
+            /usr/lib/command-not-found -- "$1"
+                        return $?
+                      elif [ -x /usr/share/command-not-found/command-not-found ]; then
+            /usr/share/command-not-found/command-not-found -- "$1"
+                        return $?
+          else
+            printf "%s: command not found\n" "$1" >&2
+            return 127
+          fi
+        }
+      fi
+      export SHELL=/bin/bash
+      export PATH=$PATH:/sbin
+      export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin
+    dest: /etc/bash.bashrc
+    owner: root
+    group: root
+    mode: '0644'
+    backup: true
+  when: ansible_os_family == 'Debian'
+  tags: bashrc
 
 ### WINDOWS ###
 
